package lolmanagement;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;

public class ViewChampion extends javax.swing.JFrame {

    public ViewChampion() {
        initComponents();
        setLocationRelativeTo(null);

        pnlList.setLayout(new GridLayout(0, 4, 20, 20));
        pnlList.setBorder(new EmptyBorder(20, 20, 20, 20));

        try {
            String url = "jdbc:sqlserver://localhost:1433;"
                    + "databaseName=LOLManagement;"
                    + "encrypt=true;trustServerCertificate=true;";
            // connect database (url,user,pass)
            Connection connection = DriverManager.getConnection(url, "sa", "nguyenDUONG07122003@");

            Statement stm = connection.createStatement();
            String sql = "SELECT * FROM Champion;";

            // excute cau lenh
            ResultSet result = stm.executeQuery(sql);
            while (result.next()) {
                JPanel pnl = new ImagePanel("src/resources/images/champions/" + result.getString("Name") + ".png");
                pnl.setLayout(new BorderLayout());
                pnl.setBorder(new LineBorder(new Color(60, 60, 65), 2));

                JPanel pnlInfo = null;
                pnlInfo = new JPanel(new GridLayout(2, 1, 10, 5));
                pnlInfo.setOpaque(false);

                JLabel lblName = new JLabel(result.getString("Name"));
                lblName.setHorizontalAlignment(JLabel.CENTER);
                lblName.setFont(new Font("Roboto", 1, 16));
                lblName.setForeground(new Color(238, 228, 208));
                pnlInfo.add(lblName);

                pnl.add(pnlInfo, BorderLayout.SOUTH);

                pnlList.add(pnl);
            }
        } catch (SQLException e) {
            System.out.println("Error loading driver: " + e);
        }
    }

    // Fix kich thuoc anh
    class ImagePanel extends JPanel {

        private Image img;

        public ImagePanel(String img) {
            this(new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(200, 266, Image.SCALE_DEFAULT)).getImage());
        }

        public ImagePanel(Image img) {
            this.img = img;
            Dimension size = new Dimension(img.getWidth(null), img.getHeight(null));
            setPreferredSize(size);
            setMinimumSize(size);
            setMaximumSize(size);
            setSize(size);
            setLayout(null);
        }

        public void paintComponent(Graphics g) {
            g.drawImage(img, 0, 0, null);
        }
    }

    public void searchChampions(String searchString) {
        // Xóa các panel hiện có trong pnlList
        pnlList.removeAll();

        try {
            String url = "jdbc:sqlserver://localhost:1433;"
                    + "databaseName=LOLManagement;"
                    + "encrypt=true;trustServerCertificate=true;";
            Connection connection = DriverManager.getConnection(url, "sa", "1999");

            Statement stm = connection.createStatement();
            String sql = "SELECT * FROM Champion WHERE LOWER(Name) LIKE '%" + searchString.toLowerCase() + "%';";

            ResultSet result = stm.executeQuery(sql);
            while (result.next()) {
                JPanel pnl = new ImagePanel("src/img/" + result.getString("Name") + ".png");
                pnl.setLayout(new BorderLayout());
                pnl.setBorder(new LineBorder(new Color(60, 60, 65), 2));

                JPanel pnlInfo = new JPanel(new GridLayout(2, 1, 10, 5));
                pnlInfo.setOpaque(false);

                JLabel lblName = new JLabel(result.getString("Name"));
                lblName.setHorizontalAlignment(JLabel.CENTER);
                lblName.setFont(new Font("Roboto", 1, 16));
                lblName.setForeground(new Color(238, 228, 208));
                pnlInfo.add(lblName);

                pnl.add(pnlInfo, BorderLayout.SOUTH);

                pnlList.add(pnl);
                txtSearch.add(pnl);
            }
        } catch (SQLException e) {
            System.out.println("Error loading driver: " + e);
        }

        // Cập nhật lại giao diện
        pnlList.revalidate();
        pnlList.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlList = new javax.swing.JPanel();
        pnlSetting = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Available Champions");

        jScrollPane1.setBorder(null);

        pnlList.setBackground(new java.awt.Color(1, 10, 19));

        javax.swing.GroupLayout pnlListLayout = new javax.swing.GroupLayout(pnlList);
        pnlList.setLayout(pnlListLayout);
        pnlListLayout.setHorizontalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        pnlListLayout.setVerticalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnlList);
        pnlList.getAccessibleContext().setAccessibleName("");

        pnlSetting.setBackground(new java.awt.Color(1, 10, 19));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(195, 190, 160));
        jLabel1.setText("SEARCH AND FILTER");

        lblTitle.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(195, 190, 160));
        lblTitle.setText("AVAILABLE CHAMPIONS");

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons/search-icon.png"))); // NOI18N

        javax.swing.GroupLayout pnlSettingLayout = new javax.swing.GroupLayout(pnlSetting);
        pnlSetting.setLayout(pnlSettingLayout);
        pnlSettingLayout.setHorizontalGroup(
            pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSettingLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlSettingLayout.createSequentialGroup()
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch))
                    .addComponent(jLabel1)
                    .addComponent(lblTitle))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        pnlSettingLayout.setVerticalGroup(
            pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSettingLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(290, 290, 290))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSetting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewChampion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewChampion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewChampion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewChampion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewChampion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlList;
    private javax.swing.JPanel pnlSetting;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
